/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import common.activity_logger;
import common.fetch_data;
import common.login;
import java.awt.Color;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import common.user_management;

/**
 *
 * @author chinojen7
 */
public class login_page extends javax.swing.JFrame {

    String username, password, role;
    boolean isAuthorized = false;
    boolean updateResponse = false;
    ArrayList<String> userCacheDataList;
    String[] userCacheData;

    user_management um = new user_management();
    activity_logger al = new activity_logger();
    fetch_data fd = new fetch_data();

    /**
     * Creates new form login2
     */
    public login_page() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.hideForgotComponents();
    }

    private void hideForgotComponents() {
        forgot_pwd_panel.setVisible(false);
        btnBack.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        overall = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        header_icon = new javax.swing.JPanel();
        btnMin = new javax.swing.JPanel();
        lblMin = new javax.swing.JLabel();
        btnClose = new javax.swing.JPanel();
        lblClose = new javax.swing.JLabel();
        btnHome = new javax.swing.JPanel();
        lblHome = new javax.swing.JLabel();
        btnBack = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        forgot_pwd_panel = new javax.swing.JPanel();
        forgot_pwd_content = new javax.swing.JPanel();
        lblForgotUsername = new javax.swing.JLabel();
        lblNewPassword = new javax.swing.JLabel();
        lblConfirmPassword = new javax.swing.JLabel();
        tfForgotNewPwd = new javax.swing.JPasswordField();
        tfForgotConfirmPwd = new javax.swing.JPasswordField();
        tfForgotUsername = new javax.swing.JTextField();
        btnResetPassword = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        contentPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblPassword = new javax.swing.JTextField();
        lblLogin = new javax.swing.JLabel();
        lblUsername = new javax.swing.JTextField();
        tfUsername = new javax.swing.JTextField();
        pfPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lbltitle6 = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        lbltitle1 = new javax.swing.JLabel();
        lbltitle2 = new javax.swing.JLabel();
        lbltitle3 = new javax.swing.JLabel();
        lbltitle4 = new javax.swing.JLabel();
        lbltitle5 = new javax.swing.JLabel();
        lblSkull = new javax.swing.JLabel();
        lblForgotPwd = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        overall.setBackground(new java.awt.Color(0, 0, 0));
        overall.setLayout(new java.awt.BorderLayout());

        header.setBackground(new java.awt.Color(102, 102, 255));
        header.setLayout(new java.awt.BorderLayout());

        header_icon.setBackground(new java.awt.Color(0, 0, 0));
        header_icon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMin.setBackground(new java.awt.Color(0, 0, 0));
        btnMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMinMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMinMouseExited(evt);
            }
        });
        btnMin.setLayout(new java.awt.BorderLayout());

        lblMin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/minus_32px.png"))); // NOI18N
        btnMin.add(lblMin, java.awt.BorderLayout.CENTER);

        header_icon.add(btnMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, 50, 50));

        btnClose.setBackground(new java.awt.Color(0, 0, 0));
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCloseMouseExited(evt);
            }
        });
        btnClose.setLayout(new java.awt.BorderLayout());

        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/close_32px.png"))); // NOI18N
        btnClose.add(lblClose, java.awt.BorderLayout.CENTER);

        header_icon.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 0, 50, 50));

        btnHome.setBackground(new java.awt.Color(0, 0, 0));
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHomeMouseExited(evt);
            }
        });
        btnHome.setLayout(new java.awt.BorderLayout());

        lblHome.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblHome.setForeground(new java.awt.Color(239, 183, 183));
        lblHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHome.setText("AHHASC");
        btnHome.add(lblHome, java.awt.BorderLayout.CENTER);

        header_icon.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 110, 50));

        btnBack.setBackground(new java.awt.Color(0, 0, 0));
        btnBack.setPreferredSize(new java.awt.Dimension(50, 50));
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBackMouseExited(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/back_32px.png"))); // NOI18N

        javax.swing.GroupLayout btnBackLayout = new javax.swing.GroupLayout(btnBack);
        btnBack.setLayout(btnBackLayout);
        btnBackLayout.setHorizontalGroup(
            btnBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        btnBackLayout.setVerticalGroup(
            btnBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        header_icon.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        header.add(header_icon, java.awt.BorderLayout.LINE_END);

        overall.add(header, java.awt.BorderLayout.PAGE_START);

        forgot_pwd_panel.setBackground(new java.awt.Color(0, 0, 0));
        forgot_pwd_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        forgot_pwd_content.setBackground(new java.awt.Color(102, 102, 102));
        forgot_pwd_content.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblForgotUsername.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblForgotUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblForgotUsername.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblForgotUsername.setText("Username:");
        forgot_pwd_content.add(lblForgotUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, -1, 30));

        lblNewPassword.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblNewPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblNewPassword.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNewPassword.setText("New Password:");
        forgot_pwd_content.add(lblNewPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 110, 30));

        lblConfirmPassword.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblConfirmPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblConfirmPassword.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblConfirmPassword.setText("Confirm Password:");
        forgot_pwd_content.add(lblConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, -1, 30));

        tfForgotNewPwd.setBackground(new java.awt.Color(0, 0, 0));
        tfForgotNewPwd.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tfForgotNewPwd.setForeground(new java.awt.Color(255, 255, 255));
        forgot_pwd_content.add(tfForgotNewPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 190, 30));

        tfForgotConfirmPwd.setBackground(new java.awt.Color(0, 0, 0));
        tfForgotConfirmPwd.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tfForgotConfirmPwd.setForeground(new java.awt.Color(255, 255, 255));
        forgot_pwd_content.add(tfForgotConfirmPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 190, 30));

        tfForgotUsername.setBackground(new java.awt.Color(0, 0, 0));
        tfForgotUsername.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tfForgotUsername.setForeground(new java.awt.Color(255, 255, 255));
        forgot_pwd_content.add(tfForgotUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 190, 30));

        btnResetPassword.setBackground(new java.awt.Color(0, 0, 0));
        btnResetPassword.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnResetPassword.setForeground(new java.awt.Color(0, 255, 51));
        btnResetPassword.setText("Reset Password");
        btnResetPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnResetPasswordMouseClicked(evt);
            }
        });
        forgot_pwd_content.add(btnResetPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 190, 60));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Forgot Password Form");
        forgot_pwd_content.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 730, 80));

        forgot_pwd_panel.add(forgot_pwd_content, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 21, 750, 410));

        overall.add(forgot_pwd_panel, java.awt.BorderLayout.PAGE_END);

        contentPanel.setBackground(new java.awt.Color(0, 0, 0));
        contentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPassword.setEditable(false);
        lblPassword.setBackground(new java.awt.Color(102, 102, 102));
        lblPassword.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        lblPassword.setText("Password:");
        lblPassword.setBorder(null);
        jPanel1.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 80, 30));

        lblLogin.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblLogin.setForeground(new java.awt.Color(255, 255, 255));
        lblLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogin.setText("AHHASC LOGIN");
        jPanel1.add(lblLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 210, -1));

        lblUsername.setEditable(false);
        lblUsername.setBackground(new java.awt.Color(102, 102, 102));
        lblUsername.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        lblUsername.setText("Username:");
        lblUsername.setBorder(null);
        jPanel1.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 80, 30));

        tfUsername.setBackground(new java.awt.Color(0, 0, 0));
        tfUsername.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        tfUsername.setForeground(new java.awt.Color(255, 255, 255));
        tfUsername.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tfUsername.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(tfUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, 220, 30));

        pfPassword.setBackground(new java.awt.Color(0, 0, 0));
        pfPassword.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        pfPassword.setForeground(new java.awt.Color(255, 255, 255));
        pfPassword.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        pfPassword.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(pfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, 220, 30));

        btnLogin.setBackground(new java.awt.Color(0, 0, 0));
        btnLogin.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("AUTHENTICATE & LOGIN");
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
        });
        jPanel1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, 220, 50));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbltitle6.setBackground(new java.awt.Color(0, 0, 0));
        lbltitle6.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        lbltitle6.setForeground(new java.awt.Color(255, 0, 204));
        lbltitle6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbltitle6.setText("'Em!\"");
        jPanel2.add(lbltitle6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 50, 40));

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logo.png"))); // NOI18N
        jPanel2.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 350, 200));

        lbltitle1.setBackground(new java.awt.Color(0, 0, 0));
        lbltitle1.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        lbltitle1.setForeground(new java.awt.Color(255, 51, 51));
        lbltitle1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbltitle1.setText("\"You ");
        jPanel2.add(lbltitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, 40));

        lbltitle2.setBackground(new java.awt.Color(0, 0, 0));
        lbltitle2.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        lbltitle2.setForeground(new java.awt.Color(255, 153, 0));
        lbltitle2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltitle2.setText("Break");
        jPanel2.add(lbltitle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 60, 40));

        lbltitle3.setBackground(new java.awt.Color(0, 0, 0));
        lbltitle3.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        lbltitle3.setForeground(new java.awt.Color(255, 255, 0));
        lbltitle3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbltitle3.setText("'Em,");
        jPanel2.add(lbltitle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 50, 40));

        lbltitle4.setBackground(new java.awt.Color(0, 0, 0));
        lbltitle4.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        lbltitle4.setForeground(new java.awt.Color(51, 255, 0));
        lbltitle4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbltitle4.setText("We");
        jPanel2.add(lbltitle4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 40, 40));

        lbltitle5.setBackground(new java.awt.Color(0, 0, 0));
        lbltitle5.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        lbltitle5.setForeground(new java.awt.Color(51, 255, 204));
        lbltitle5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbltitle5.setText("Fix");
        jPanel2.add(lbltitle5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 30, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 370, 350));

        lblSkull.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSkull.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/skull.png"))); // NOI18N
        jPanel1.add(lblSkull, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 290, 20, 20));

        lblForgotPwd.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        lblForgotPwd.setForeground(new java.awt.Color(255, 255, 255));
        lblForgotPwd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblForgotPwd.setText("Forgor Your Password?");
        lblForgotPwd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblForgotPwdMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblForgotPwdMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblForgotPwdMouseExited(evt);
            }
        });
        jPanel1.add(lblForgotPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 290, 250, 20));

        contentPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 740, 370));

        overall.add(contentPanel, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(overall, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(overall, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void changeColor(JPanel hover, Color rand) {
        hover.setBackground(rand);
    }

    public void changeFontColor(JLabel hover, Color rand) {
        hover.setForeground(rand);
    }

    public void setLoginDetails() {
        this.username = this.tfUsername.getText();
        this.password = this.pfPassword.getText();
    }

    public void authenticateUser() {
        this.setLoginDetails();

        login validateFunction = new login();
        this.isAuthorized = validateFunction.accountValidator(this.username, this.password);
    }

    private void btnMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btnMinMouseClicked

    private void btnMinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinMouseEntered
        changeColor(btnMin, new Color(239, 183, 183, 255));
    }//GEN-LAST:event_btnMinMouseEntered

    private void btnMinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinMouseExited
        changeColor(btnMin, new Color(0, 0, 0));
    }//GEN-LAST:event_btnMinMouseExited

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        if (JOptionPane.showConfirmDialog(null, "Are You Sure You Want to Leave?", "Goodbye? :(", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(null, "Stay Safe and Goodbye Now! :')", "Goodbye", JOptionPane.INFORMATION_MESSAGE);
            System.exit(0); //Exit 
        } else {
            //Remain in Application
        }
    }//GEN-LAST:event_btnCloseMouseClicked

    private void btnCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseEntered
        changeColor(btnClose, new Color(255, 105, 180));
    }//GEN-LAST:event_btnCloseMouseEntered

    private void btnCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseExited
        changeColor(btnClose, new Color(0, 0, 0));
    }//GEN-LAST:event_btnCloseMouseExited

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked

    }//GEN-LAST:event_btnHomeMouseClicked

    private void btnHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseEntered
        this.changeFontColor(lblHome, new Color(255, 255, 255));
    }//GEN-LAST:event_btnHomeMouseEntered

    private void btnHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseExited
        this.changeFontColor(lblHome, new Color(239, 183, 183, 255));
    }//GEN-LAST:event_btnHomeMouseExited

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
        this.authenticateUser();

        if (this.isAuthorized == true) {

            try {
                this.userCacheDataList = fd.fetchSession();
                this.userCacheData = userCacheDataList.toArray(new String[0]);
                this.role = userCacheData[2];

                al.logUserActivity(userCacheData[0], "Logged In");
            } catch (IOException ex) {
                Logger.getLogger(login_page.class.getName()).log(Level.SEVERE, null, ex);
            }

            if (this.role.equals("Manager")) {
                JOptionPane.showMessageDialog(null, "Welcome Back " + this.role + " " + this.username + "!", "Login Successful", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
                try {
                    manager_mm mmm = new manager_mm();
                    mmm.setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(login_page.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Welcome Back " + this.role + " " + this.username, "Login Successful", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
                try {
                    technician_mm tmm = new technician_mm();
                    tmm.setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(login_page.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

        } else {
            JOptionPane.showMessageDialog(null, "Your Username or Password is False, Please Try Again!", "Login Failed", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnLoginMouseClicked

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        this.hideForgotComponents();
    }//GEN-LAST:event_btnBackMouseClicked

    private void btnBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseEntered
        changeColor(btnBack, new Color(255, 0, 153));
    }//GEN-LAST:event_btnBackMouseEntered

    private void btnBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseExited
        changeColor(btnBack, new Color(0, 0, 0));
    }//GEN-LAST:event_btnBackMouseExited

    private void lblForgotPwdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblForgotPwdMouseClicked
        forgot_pwd_panel.setVisible(true);
        btnBack.setVisible(true);
    }//GEN-LAST:event_lblForgotPwdMouseClicked

    private void lblForgotPwdMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblForgotPwdMouseEntered
        changeFontColor(lblForgotPwd, new Color(0, 255, 255));
    }//GEN-LAST:event_lblForgotPwdMouseEntered

    private void lblForgotPwdMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblForgotPwdMouseExited
        changeFontColor(lblForgotPwd, new Color(255, 255, 255));
    }//GEN-LAST:event_lblForgotPwdMouseExited

    private void btnResetPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetPasswordMouseClicked
        if (um.validatePasswordField(tfForgotNewPwd)) {
            if (!tfForgotNewPwd.getText().equals(tfForgotConfirmPwd.getText())) {
                JOptionPane.showMessageDialog(null, "New Password and Confirm Password does not match.", "Passwords don't match", JOptionPane.ERROR_MESSAGE);
            } else {
                try {
                    this.updateResponse = this.um.updateForgotPassword(tfForgotUsername.getText(), tfForgotNewPwd.getText());
                    JOptionPane.showMessageDialog(null, "Resetting Password in Progress...", "Resetting Password", JOptionPane.INFORMATION_MESSAGE);

                    if (this.updateResponse == true) {
                        JOptionPane.showMessageDialog(null, "Password Reset is Successful, You can Login Now!", "Reset Password Successful", JOptionPane.INFORMATION_MESSAGE);
                        al.logUserActivity(tfForgotUsername.getText(), "Resetted Password");
                        this.hideForgotComponents();
                    } else {
                        JOptionPane.showMessageDialog(null, "Username Provided Don't Exist, Please Try Again!", "Username Provided Don't Exist", JOptionPane.ERROR_MESSAGE);
                    }
                } catch (IOException ex) {
                    Logger.getLogger(login_page.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please check your inputs again!", "Password Validation Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnResetPasswordMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnBack;
    private javax.swing.JPanel btnClose;
    private javax.swing.JPanel btnHome;
    private javax.swing.JButton btnLogin;
    private javax.swing.JPanel btnMin;
    private javax.swing.JButton btnResetPassword;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JPanel forgot_pwd_content;
    private javax.swing.JPanel forgot_pwd_panel;
    private javax.swing.JPanel header;
    private javax.swing.JPanel header_icon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblConfirmPassword;
    private javax.swing.JLabel lblForgotPwd;
    private javax.swing.JLabel lblForgotUsername;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMin;
    private javax.swing.JLabel lblNewPassword;
    private javax.swing.JTextField lblPassword;
    private javax.swing.JLabel lblSkull;
    private javax.swing.JTextField lblUsername;
    private javax.swing.JLabel lbltitle1;
    private javax.swing.JLabel lbltitle2;
    private javax.swing.JLabel lbltitle3;
    private javax.swing.JLabel lbltitle4;
    private javax.swing.JLabel lbltitle5;
    private javax.swing.JLabel lbltitle6;
    private javax.swing.JPanel overall;
    private javax.swing.JPasswordField pfPassword;
    private javax.swing.JPasswordField tfForgotConfirmPwd;
    private javax.swing.JPasswordField tfForgotNewPwd;
    private javax.swing.JTextField tfForgotUsername;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables
}
